package chapters.Chapter3;

public class A_README {

	public static void main(String[] args) {
	
	//ANSWERS OF QUESTIONS 09-13-15-27-32-34 ARE MISSING. 
	//IN SOME QUESTIONS, I COULDN'T FIGURE OUT, WHICH ALGORIYTHM TO USE, (9-13-15)
	//IN SOME OTHER QUESTIONS, BECAUSE OF MY LACK OF GEOMETRY KNOWLEDGE, I COULDN'T ANSWER THAT QUESTIONS.. (27-32-34)
	//SORRY FOR MISSING ANSWERS..

	}

}
